# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
   
    - name: Go Get 1
      run: go get golang.org/x/crypto/chacha20poly1305
    - name: Go Get 2
      run: go get golang.org/x/crypto/openpgp
    - name: Go Get 3
      run: go get golang.org/x/crypto/openpgp/armor
    - name: Go Get 4
      run: go get golang.org/x/crypto/openpgp/packet

    - name: Build
      run: go build -v 

    - name: Test
      run: go test -v 
